version: "3.0"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"  # Основной порт Ollama
    volumes:
      - ./ollama_data:/root/.ollama  # Для хранения моделей
    networks:
      - app-network
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      ollama serve &
      sleep 10  # Даем время на запуск сервера
      ollama run yandex/YandexGPT-5-Lite-8B-instruct-GGUF
      wait 

  db:
    image: postgres:15
    container_name: db-store
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-store
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - /etc/nginx/sites-available/tenderhack.conf:/etc/nginx/conf.d/default.conf  # Ваша оригинальная конфигурация
    ports:
      - "80:80"
    depends_on:
      - app
      - frontend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: ./backend
    container_name: app-store
    environment:
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - JWT_SECRET=812659050808fd763749156b9b403c46a2338f082b4cc1316d3b0ac8794937aa
      - JWT_ACCESS_TOKEN_TIME=10000
      - JWT_ALGORITHM=HS256
      - JWT_REFRESH_TOKEN_TIME=3
      - NEXT_PUBLIC_API_BASE_URL="/api/v1/"
      - NEXT_PUBLIC_WS_BASE_URL="/api/v1/"
      - OLLAMA_BASE_URL="http://ollama:11434"  # Подключение к Ollama внутри сети
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network
    depends_on:
      - db
      - ollama
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data:  # Том для хранения моделей Ollama